<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=1,initial-scale=1,user-scalable=1" />
    <title>Cezar's Tecno Shop </title>

    <link href="http://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="css/styles.css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<section class="container">
    <section class="login-form">

        <section>
            <img src="img/logo.png" alt="" />
        </section>
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="post" action="" role="login">
                    <div class="form-group">
                        <label>Usuário</label>
                        <input type="user" name="email" required class="form-control" />
                    </div>

                    <div class="form-group">
                        <label>Senha</label>
                        <input type="password" name="password" required class="form-control" />
                    </div>

                    <input type="checkbox" name="remember" value="1" /> Manter logado?
                    <button type="submit" name="go" class="btn btn-primary btn-block">Entrar</button>
                </form>
            </div>
            <div class="panel-footer">
                <a href="#">Esqueceu a senha?</a>
            </div>

        </div>
        <section>
            <a href="#">&larr; Voltar a loja</a>
        </section>

    </section>
</section>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>